server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/random-coffee
    username: postgres
    password: 357
    driver-class-name: org.postgresql.Driver

#  security:
#    user:
#      name: admin
#      password: admin

  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
#        ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 10
          lob:
            non_contextual_creation: true

logging:
  level:
    org:
      hibernate:
        type: trace



#app:
#  base-url: itmo.ru